acmucsd/hackathon-portal

- authService.ts
- firebaseConfig.ts
- index.ts
- package.json
- yarn.lock
Closes **#5**.
Set up a Firebase Console for the Hackathon Portal here: https://console.firebase.google.com/project/hackathon-portal-2beea/overview
Wrote code to implement sign up, login, and forgot password functionality for the portal using email/password. Also tested sign up and login methods.
- `firebaseConfig.ts`: initializing Firebase with configuration keys
- `authService.ts`: frontend auth methods for register, login, and forgot password functionalities
- `index.ts`: testing done to ensure that functions work
expected)
If you've selected Patch, Minor, or Major as your change type, **make sure to bump the version before merging in …
> Set up firebase auth (firebase admin todo)

- .env.example
- README.md
- firebaseConfig.ts
- services/FirebaseService.ts
> Cleanup Firebase, add setup instructions in README

- .vscode/settings.json
- server/DataSource.ts
- server/api/controllers/UserController.ts
- server/api/controllers/index.ts
- server/config/index.ts
- server/firebaseConfig.ts
- server/index.ts
- server/package.json
- server/yarn.lock
Closes **#10**.
[description]
- [Fill in here]
expected)
> Add express and controller routing

- server/README.md
- server/models/ResponseModel.ts
- server/models/UserModel.ts
- server/models/index.ts
- server/repositories/ResponseRepository.ts
- server/repositories/index.ts
- server/services/ResponseService.ts
- server/types/Enums.ts
- Added TypeORM code for response tables
expected)
> Add Response table for Postgres

- server/api/controllers/UserController.ts
- server/api/validators/UserControllerRequests.ts
- server/config/index.ts
- server/services/UserService.ts
- server/types/ApiRequests.ts
- server/types/ApiResponses.ts
I tested this on Postman and it works trust me
login route
get current user route
> Backend: Implement login

- server/DataSource.ts
- server/api/controllers/ResponseController.ts
- server/api/controllers/index.ts
- server/api/decorators/Validators.ts
- server/api/middleware/UserAuthentication.ts
- server/api/middleware/index.ts
- server/api/validators/ResponseRequests.ts
- server/index.ts
- server/repositories/ResponseRepository.ts
- server/services/ResponseService.ts
- server/services/UserService.ts
- server/types/ApiResponses.ts
- server/types/Application.ts
- server/types/Enums.ts
> Backend: Application Submission

- server/FirebaseAuth.ts
- server/MigrationDataSource.ts
- server/api/controllers/UserController.ts
- server/api/middleware/ErrorHandler.ts
- server/api/middleware/index.ts
- server/config/index.ts
- server/index.ts
- server/migrations/001-add-user-table.ts
- server/migrations/002-add-response-table.ts
- server/models/ResponseModel.ts
- server/models/UserModel.ts
- server/package.json
- server/services/UserService.ts
- server/types/ApiResponses.ts
- server/types/Enums.ts
- server/yarn.lock
Closes **[ISSUE NUMBER]**. (If there is no issue for this pull request yet, please create one or
- Added migrations, MigrationDataSource, migration commands
- Reorganized firebase auth and admin auth into separate file
- Return user responses if already on model
- Updated some packages
- Formatting changes
expected)
Please include a screenshot of your Postman testing passing …
> Migrations + Refactoring

- .github/workflows/backend-deploy.yml
- captain-definition
> deploy stuff

- client/src/app/login/page.tsx
- client/src/components/Dashboard/index.tsx
- client/src/components/Navbar/index.tsx
- client/src/components/Navbar/style.module.scss
- client/src/config.tsx
- remove forgot password
- fix dates
- remove irrelevant faq
-
> fix bugs frontend

- server/services/UserService.ts
- server/types/ApiRequests.ts
- server/types/ApiResponses.ts
Not that important but simplified email verification step by using library calls instead of REST API calls.
[description]
- [Fill in here]
expected)
> Simplified email verification

- client/src/components/Profile/index.tsx
Closes **54**. (If there is no issue for this pull request yet, please create one or
- Fixed bug with profile changes not updating on front-end
- Added useState to store user info
expected)
> Fixed Profile Changes Bug

- client/src/components/ApplicationReview/index.tsx
- client/src/components/DashboardStatus/index.tsx
- Change text based on user status
- Automatically add a + on application submission for phone number if user forgot it
- refresh router before navving back to guarantee that app status updates
> Frontend: Dashboard status text, application tweaks

- server/api/controllers/UserController.ts
- server/api/validators/UserControllerRequests.ts
- server/services/UserService.ts
- server/types/ApiRequests.ts
- server/types/ApiResponses.ts
Closes **#81**. (If there is no issue for this pull request yet, please create one or
Created backend POST route for forgot password functionality. Sends the user an email to their intended email address with a link to reset their password.
- `UserController.ts`
- `UserService.ts`
expected) …
> sending forgot password link to email

- client/src/app/register/page.tsx
- client/src/components/Profile/index.tsx
- server/api/decorators/Validators.ts
Added .ca as valid edu email
expected)
> Allow .ca emails

- server/DataSource.ts
- server/api/controllers/AdminController.ts
- server/services/UserService.ts
Closes **#88**. (If there is no issue for this pull request yet, please create one or
Adds GET routes for Admin dashboard to get all users and getting user + their associated application.
- `AdminController.ts`
- `UserService.ts`
expected)
https://github.com/user-attachments/assets/e998ffb0-e81d-4842-b60f-bab215c913 …
> admin get all users and get user + app routes

- client/src/components/ApplicationStep/index.tsx
Closes **#91**
- Added conditional text field input when "Other" is selected for University Dropdown
- Changed dropdown input to include option to render text field
expected)
https://github.com/user-attachments/assets/a5cf87d5-312b-4121-9214-cc833884f3e0
> Updated University Dropdown for Other Universities

- server/api/validators/ResponseRequests.ts
- server/package.json
- server/types/Application.ts
Closes #86 
Added "motivation" field to application for why question
Also enforced required questions
expected)
Note the motivation field.
Error if missing required field.
> Add why question

- client/src/app/applicationView/[id]/page.tsx
- client/src/components/StatusTag/index.tsx
- client/src/components/StatusTag/style.module.scss
- client/src/components/admin/ApplicationView/index.tsx
- client/src/components/admin/ApplicationView/style.module.scss
- client/src/lib/api/AdminAPI.ts
- client/src/lib/types/apiResponses.ts
- client/src/lib/types/enums.ts
Closes **#102**
Allows admin to update application decisions for users
- Added buttons to review application
- Changed status tag for application status/decision
expected)
https://github.com/user-attachments/assets/299f88db-a247-4b9a-8ae5-24e285b5963a
> Review Applications

- client/src/app/login/login.ts
- client/src/app/login/page.tsx
Closes #79. (If there is no issue for this pull request yet, please create one or
Moved API logout call until after setting error message
- Fixed bug where "invalid password" would no longer show
expected)
https://github.com/user-attachments/assets/413ab75e-a3d7-4a76-b00e-9a8ff8b64c17
> Fixed invalid password not showing after cookie clears

- server/api/controllers/ResponseController.ts
- server/services/PermissionsService.ts
Closes **[ISSUE NUMBER]**. (If there is no issue for this pull request yet, please create one or
[description]
- [Fill in here]
expected)
> Close application routes

- server/api/controllers/EventController.ts
- server/api/controllers/index.ts
- server/api/validators/EventControllerRequests.ts
- server/api/validators/GenericRequests.ts
- server/migrations/005-add-event-table.ts
- server/models/EventModel.ts
- server/models/index.ts
- server/package.json
- server/repositories/EventRepository.ts
- server/repositories/index.ts
- server/services/EventService.ts
- server/services/PermissionsService.ts
- server/types/ApiRequests.ts
- server/types/ApiResponses.ts
- server/types/Enums.ts
Closes #109 
Events model, repository, service, controller, types, migrations, etc.
- [Fill in here]
expected)
> Backend events setup

- client/src/app/admin/page.tsx
- client/src/app/manageUsers/page.module.scss
- client/src/components/Table/style.module.scss
- client/src/components/admin/AdminDashboard/index.tsx
- client/src/components/admin/ApplicationView/style.module.scss
- client/src/components/admin/UserItem/index.tsx
- client/src/components/admin/UserRow/index.tsx
- client/src/components/admin/UsersDashboard/index.tsx
- client/src/lib/api/AdminAPI.ts
- client/src/lib/types/apiResponses.ts
Closes **#102**. (If there is no issue for this pull request yet, please create one or
Changed users table to include application decisions
- Redirected button on admin dashboard to manage users page
- Show application decisions instead of status on table 
expected)
- [] I have appropriately edited the API version in the `package.json` file. …
> Review Applications Dashboard

- client/src/components/admin/UsersDashboard/index.tsx
Fixed filter to search for full name
- Changed conditional to allow admins to search full name instead of first name/last name individually
expected)
https://github.com/user-attachments/assets/36903a94-c08a-42b1-8f71-0fe46ea1340e
> Fix for Searching Names

- client/src/components/DashboardStatus/index.tsx
fixing dashboard writing for accepted/confirmed people
- removing that confirm acceptance button since it doesn't do anything ...
> fix dashboard copywriting

- client/src/app/admin/page.module.scss
- client/src/app/admin/scan/page.module.scss
- client/src/app/applicationView/[id]/page.module.scss
- client/src/app/apply/[step]/page.module.scss
- client/src/app/check-email/page.module.scss
- client/src/app/check-reset-email/page.module.scss
- client/src/app/createEvent/page.module.scss
- client/src/app/forgot-password/page.module.scss
- client/src/app/liability/page.module.scss
- client/src/app/login/page.module.scss
- client/src/app/manageEvents/page.module.scss
- client/src/app/manageUsers/page.module.scss
- client/src/app/modifyEvent/[uuid]/page.module.scss
- client/src/app/page.module.scss
- client/src/app/photoRelease/page.module.scss
- client/src/app/profile/page.module.scss
- client/src/app/register/page.module.scss
- client/src/app/resources/page.module.scss
- client/src/components/Navbar/index.tsx
- client/src/components/admin/AdminDashboard/index.tsx
- client/src/components/admin/AdminDashboard/style.module.scss
- client/src/styles/globals.scss
- client/src/styles/vars.scss
> Simplify admin dashboard, fix mobile padding

- client/src/components/EventRow/index.tsx
- client/src/components/TableCell/style.module.scss
- client/src/components/ToggleSwitch/index.tsx
- client/src/components/admin/EventForm/index.tsx
Closes **[ISSUE NUMBER]**. (If there is no issue for this pull request yet, please create one or
Added accordion to user schedule and fixed published status for modifying events
- Accordion visible for desktop on user schedule
- Changed toggle switch to show default value
- Made line height taller for longer event titles
expected)
> Event schedule bug fixes

- client/src/components/Typography/index.tsx
- client/src/components/Typography/style.module.scss
makes mobile easier to look at
didn't do all the sizes, just the ones we use
> add scaling for mobile fonts

- client/src/app/admin/scan/page.tsx
- client/src/components/admin/CheckIn/index.tsx
> add dropdown fallback for checkin in case qrs brick or smth

- client/src/components/admin/CheckIn/index.tsx
remove day since we can just name the events better lol
> tiny tweak to checkin event dropdown

- client/public/assets/heistscene.svg
- client/src/app/api/logout/route.ts
- client/src/app/closed/page.module.scss
- client/src/app/closed/page.tsx
- client/src/middleware.ts
Added closed page to redirect users to when hackathon is over
- Added page with closed info
expected)
https://github.com/user-attachments/assets/29ae8a10-3624-4163-a2e2-bbddf6a7f8e0
> Added Closed Page
